version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs/certs/server:/etc/nginx/certs/server/
      - ./certs/certs/ca:/etc/nginx/certs/ca/
    ports:
      - 443:443

  webapp:
    build:
      context: .
      dockerfile: Dockerfile.webapp
